CREATE TABLE banks (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    bank_name VARCHAR(100) NOT NULL,
    color VARCHAR(100) NOT NULL,
    image TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
